### ISSUE TITLE
Naming methods: check_req_status?

### ISSUE THREAD

**Issue by soumyaray** [BurgerRoach/THSR-lib#10]
https://github.com/BurgerRoach/THSR-lib/blob/9cc1b36778074995c15ac3016779e77f241accc4/lib/api.rb#L50

I think the `check_req_status?` method could be better named.  The name doesn’t convey what its actually doing: asking if there was an error or not.  I think either `successful?` or `http_error?` or something like that is a better name as it conveys that there is success/error involved.

More generally speaking, you’ll find that ruby’s flexible naming rules allow you to avoid starting method names with `check_`, `get_` or `set_`.

**Comment by music1353** [comment]
I've got it! It's really useful to use a question mark to express the meaning of a check. Thanks!

**Comment by soumyaray** [comment]
nicely done!
