### ISSUE TITLE
renaming check_opts method and raising errors more cleanly

### ISSUE THREAD

**Issue by soumyaray** [BurgerRoach/THSR-lib#11]
https://github.com/BurgerRoach/THSR-lib/blob/9cc1b36778074995c15ac3016779e77f241accc4/lib/api.rb#L23

Couple of suggestions on this otherwise nice use of the Errors module!

First, `check_opts` could be better named as `valid_options?` or `invalid_options` depending on true/false means.

After that, this line would read more easily as:

```ruby
raise Errors::OptionsError if invalid_options?(options)
```

or

```ruby
raise Errors::OptionsError unless valid_options?(options)
```

If options is something truly complicated (or gets complicated later), you could even make it a class of its own!

**Comment by music1353** [comment]
I got it! Thanks!
